spring.application.name=ThesisBackend
<<<<<<< HEAD
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#jwt.secret=${JWT_SECRET}
#jwt.expirationMs=${JWT_EXPIRATION_MS}
=======
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}

#local


>>>>>>> 43ff0f1a30c1b11fa4c9dfc866912d9c35ea51bf

spring.data.mongodb.uri=mongodb://localhost:27017/thesisBackEndSecure
jwt.secret=Q29uc3RydWN0U2VjdXJlSldUX0tleUZvckV4YW1wbGVTcHJpbmdCb290QXBwMTIzIT8=
jwt.expirationMs=43200000

